# $FreeBSD: head/devel/pybugz/Makefile 345623 2014-02-22 10:50:28Z mva $

PORTNAME=	pybugz
PORTVERSION=	0.9.3
PORTREVISION=	2
CATEGORIES=	devel
MASTER_SITES=	http://www.bayofrum.net/dist/${PORTNAME}/
PKGNAMEPREFIX=	${PYTHON_PKGNAMEPREFIX}

MAINTAINER=	crees@FreeBSD.org
COMMENT=	Command line tools for interacting with Bugzilla

LICENSE=	GPLv2

WRKSRC=		${WRKDIR}/${PORTNAME}
USE_PYTHON=	2
USE_PYDISTUTILS=yes
PYDISTUTILS_AUTOPLIST=	yes

.include <bsd.port.mk>
