# Created by: gno@yahoo-inc.com
# $FreeBSD: ports/devel/json-c/Makefile,v 1.9 2012/12/15 08:22:13 svnexp Exp $

PORTNAME=	json-c
PORTVERSION=	0.10
CATEGORIES=	devel
MASTER_SITES=	https://s3.amazonaws.com/json-c_releases/releases/

MAINTAINER=	gno@yahoo-inc.com
COMMENT=	JSON (JavaScript Object Notation) implementation in C

USE_LDCONFIG=	yes
GNU_CONFIGURE=	yes
USE_GMAKE=	yes
USE_GNOME=	pkgconfig gnomehack

CONFLICTS=	cocaine-core-[0-9]*

.include <bsd.port.mk>
